check_for_license_expirations:
  cron: "*/10 * * * *" # Every 10 mins (https://crontab.guru/every-10-minutes)
  class: "LicenseExpirationsWorker"

check_for_license_overdue_check_ins:
  cron: "*/10 * * * *" # Every 10 mins
  class: "LicenseOverdueCheckInsWorker"

report_account_request_limits:
  cron: "0 0 * * *" # Every day at midnight (6pm CST)
  class: "RequestLimitsReportWorker"

prune_request_logs:
  cron: "0 3 * * *" # Every day at 3am (9pm CST)
  class: "PruneRequestLogsWorker"

prune_metrics:
  cron: "0 4 * * *" # Every day at 4am (10pm CST)
  class: "PruneMetricsWorker"

prune_webhook_events:
  cron: "0 5 * * *" # Every day at 5am (11pm CST)
  class: "PruneWebhookEventsWorker"

vacuum_analyze_webhook_events:
  cron: "0 7 * * *" # Every day at 7am (1am CST)
  class: "VacuumAnalyzeWebhookEventsWorker"

vacuum_analyze_metrics:
  cron: "0 8 * * *" # Every day at 8am (2am CST)
  class: "VacuumAnalyzeMetricsWorker"

vacuum_analyze_request_logs:
  cron: "0 9 * * *" # Every day at 9am (3am CST)
  class: "VacuumAnalyzeRequestLogsWorker"
